--EJERCICIO 1
VAR B_NOM VARCHAR2(20);
VAR B_PORC_BON NUMBER;

EXEC :B_NOM := 'MARCO OGAZ VARAS';
EXEC :B_PORC_BON := 40;


DECLARE
    V_SUELDO_EMP NUMBER(20);
    V_BONO NUMBER(20);
    V_RUN NUMBER(20);
BEGIN

    SELECT
        SUELDO_EMP, SUELDO_EMP * :B_PORC_BON /100, NUMRUT_EMP
        INTO 
        V_SUELDO_EMP, V_BONO, V_RUN
    FROM
        EMPLEADO
    WHERE NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP = :B_NOM;
    
    DBMS_OUTPUT.PUT_LINE('DATOS CALCULO BONIFICACION EXTRA DEL '||:B_PORC_BON||'% DEL SUELDO');
    DBMS_OUTPUT.PUT_LINE('NOMBRE EMPLEADO: '||:B_NOM);
    DBMS_OUTPUT.PUT_LINE('RUN: '||V_RUN);
    DBMS_OUTPUT.PUT_LINE('SUELDO: '||V_SUELDO_EMP);
    DBMS_OUTPUT.PUT_LINE('BONIFICACION EXTRA: '||V_BONO);

END;
/

SET SERVEROUTPUT ON;