PACKAGE
1. UN BLOQUE PLSQL CON NOMBRE QUE AGRUPA COMPONENTES QUE DE ALGUNA FORMA TIENEN UNA
RELACION LOGICA (A QUE LOS COMPONENTES SE USAN PARA UN RPOCESO, QUE SE USAN PARA
CONSULTAS DE UNA MISMA APLICACIÓN, ETC.)
TÉCNICAMENTE A LOS COMPONENTES DEL PACKAGE SE LES LLAMA CONSTRUCTORES.
2. LOS CONSTRUCTORES DEL PACKAGE PUEDEN SER:
-VARIABLES
    -CURSORES
    -PROCEDIMIENTOS (NO ALMACENADOS)
    -FUNCIONES (NO ALMACENADAS)
    -EXCEPCIONES
3. EL PACKAGE CONSTA DE 2 PARTES: 
    -ESPECIFICACION DEL PACKAGE: TODOS LOS CONSTRUCTORES QUE SE DEFINEN
    EN LA ESPECIFICACION SON PUBLICOS. ESTO SIGNIFICA QUE ESOS CONSTRUCTORES
    SE PUEDEN USAR EN CUALQUIER PROCESO, DESDE CUALQUIER APLICACION CONSTRUIDA
    EN OTRO LENGUAJE (EJ JAVA).
    
    -EL CUERPO DEL PACKAGE: DEFINIR VARIABLES (NO SON PÚBLICAS),
    ESTO SIGNIFICA QUE SOLO SE PUEDEN USAR EN EL CUERPO DEL PACKAGE,
    LA DEFINICION DE PROCEDIMENTOS Y FUNCIONES DEFINIDAS EN LA ESPECIFICACION DEL 
    PACKAGE
    
4. PARA REFERENCIAR A ALGUN CONSTRUCTOR DESDE UN PROGRAMA PLSQL, DESDE UNA SENTENCIA
SQL O DESDE UNA APLICACIÓN SE DEBE REALIZAR DE LA SIGUIENTE FORMA:

    NOMBRE_PACKAGE.NOMBRE_CONSTRUCTOR

5. NO PUEDE EXISTIR UN CUERPO DE PACKAGE SIN UNA ESPECIFICACIÓN, PERO PUEDE EXISTIR
UNA ESPECIFICACIÓN DE PACKAGE SIN UN CUERPO. EJEMPLO CUANDO SÓLO SE DEFINEN VARIABLES
EN EL PACKAGE, SOLO SE REQUIERE DE LA ESPECIFICACIÓN DEL PACKAGE Y NO DEL CUERPO

6. PARA CREAR LA ESPECIFICACIÓN DEL PACKAGE
    CREATE OR REPLACE PACKAGE PKG_NOMBRE_PACKAGE IS
    DECLARACIÓN DE VARIABLES
    DECLARACIÓN DE TIPOS
    ESPECIFICACIÓN DE FUNCIONES
    ESPECIFICACIÓN PROCEDIMIENTOS

END PKG_NOMBRE_PACKAGE;


–EJEMPLO CON HR

CREATE SEQUENCE SEQ_ERROR_PROC;

CREATE TABLE ERROR_PROCESO
(correlativo NUMBER(3),
 rutina_error VARCHAR2(250),
 mensaje_error VARCHAR2(250));
