1. PARA QUE UN BLOQUE PLSQL PUEDA SER EJECUTADO DESDE OTRAS APLICACIONES Y/O DESDE OTROS PROCESOS PLSQL
EL BLOQUE DEBE ESTAR ALMACENADO EN LA BASE DE DATOS.

2. CUANDO UN BLOQUE PLSQL SE ALMACENA EN LA BASE DE DATOS SE LLAMA PROGRAMA PL/SQL
O BLOQUE PL/SQL CON NOMBRE

3. LOS PROGRAMAS PL/SQL O BLOQUES CON NOMBRE SON:

    -PROCEDIMIENTOS ALMACENADOS CUYO OBJETIVO ES PROCESAR INFORMACION MASIVA.
    POR LO TANTO DEBERIA TENER CURSORES EXPLICITOS, REALIZAR CALCULOS, OBTENER DATOS
    DE OTRAS TABLAS, INSERTAR RESULTADO DEL PROCESO. HAY UNA EXCEPCION A ESTO 
    Y ES CUANDO SE USA UN PROCEDIMIENTO PARA INSERTAR RESULTADO EN TABLAS
   
    -FUNCIONES ALMACENADAS: CUYO OBJETIVO ES QUE A PARTIR DE UNO O VARIOS PARAMETROS
    LA SENTENCIA OBTENGA UN VALOR Y LO RETORNE
    
    -PACKAGE: CUYO OBJETIVO ES AGRUPAR PROGRAMAS SQL PARA UN PROCESO. ESTO ES PORQUE LA EJECUCION ES 
    MAS RAPIDA. 
    
    -TRIGGER: CUYO OBJETIVO ES REALIZAR UNA ACCION DE ACUERDO A LA SENTENCIA SQL EJECUTADA EN 
    LA TABLA ASOCIADA AL TRIGGER.

    -PARA CREAR ESTOS PROGRAMAS:
    CREATE OR REPLACE TIPO_PROGRAMA NOMBRE_PROGRAMA(PARAMETROS) IS
    
    -PARA QUE EL USUARIO PUEDA CREAR ESTOS PROGRAMAS DEBE TENER EL PRIVILEGIO DE 
    CREATE TIPO_PROGRAMA
    
    -TODOS LOS PROGRAMAS DEPENDEN DE LOS OBJETOS A LOS QUE HACEN REFERENCIA, SI EL O LOS
    OBJETOS QUE SE REFERENCIAN NO EXISTEN EL PROGRAMA SE DESCOMPILA Y NO SE PUEDE EJECUTAR,
