PACKAGE
1. UN BLOQUE PLSQL CON NOMBRE QUE AGRUPA COMPONENTES QUE DE ALGUNA FORMA TIENEN UNA
RELACION LOGICA (A QUE LOS COMPONENTES SE USAN PARA UN RPOCESO, QUE SE USAN PARA
CONSULTAS DE UNA MISMA APLICACIÓN, ETC.)
TÉCNICAMENTE A LOS COMPONENTES DEL PACKAGE SE LES LLAMA CONSTRUCTORES.
2. LOS CONSTRUCTORES DEL PACKAGE PUEDEN SER:
-VARIABLES
    -CURSORES
    -PROCEDIMIENTOS (NO ALMACENADOS)
    -FUNCIONES (NO ALMACENADAS)
    -EXCEPCIONES
3. EL PACKAGE CONSTA DE 2 PARTES: 
    -ESPECIFICACION DEL PACKAGE: TODOS LOS CONSTRUCTORES QUE SE DEFINEN
    EN LA ESPECIFICACION SON PUBLICOS. ESTO SIGNIFICA QUE ESOS CONSTRUCTORES
    SE PUEDEN USAR EN CUALQUIER PROCESO, DESDE CUALQUIER APLICACION CONSTRUIDA
    EN OTRO LENGUAJE (EJ JAVA).
