-- EJERCICIO TIPO PRUEBA
VAR B_VAL_CARGA_FAMI NUMBER;
VAR B_MOV_ADICIONAL NUMBER;
VAR B_VAL_COLACION NUMBER;
VAR B_FECHA_PROCESO VARCHAR2;

EXEC :B_VAL_CARGA_FAMI:=4500;
EXEC :B_MOV_ADICIONAL:= 25000;
EXEC :B_VAL_COLACION:=40000;
EXEC :B_FECHA_PROCESO:='28/02/2023';