VAR B_VAL_CARGA_FAMILIAR NUMBER;
VAR B_MONTO_MOVI NUMBER;
VAR B_FECHA_PROCESO VARCHAR2;
VAR B_VAL_TOPE_HABERES_ASIG_FAMILIAR NUMBER;
VAR B_PORC_COMISION_VENTAS NUMBER;
--
VAR B_VAL_TOPE_HABERES_ASIG_MOVI NUMBER;
EXEC :B_VAL_CARGA_FAMILIAR:= 6300;
EXEC :B_FECHA_PROCESO:= '12/2023';
EXEC :B_VAL_TOPE_HABERES_ASIG_FAMILIAR:= 405000;
EXEC :B_PORC_COMISION_VENTAS:= 40;