VAR B_VAL_CARGA_FAMILIAR NUMBER;
VAR B_MONTO_MOVI NUMBER;
VAR B_FECHA_PROCESO VARCHAR2;
VAR B_VAL_TOPE_HABERES_ASIG_FAMILIAR NUMBER;
VAR B_PORC_COMISION_VENTAS NUMBER;
--
VAR B_VAL_TOPE_HABERES_ASIG_MOVI NUMBER;
EXEC :B_VAL_CARGA_FAMILIAR:= 6300;
EXEC :B_FECHA_PROCESO:= '12/2023';
EXEC :B_VAL_TOPE_HABERES_ASIG_FAMILIAR:= 405000;
EXEC :B_PORC_COMISION_VENTAS:= 40;
DECLARE
V_ID_VENDEDOR NUMBER(5);
V_RUT_VENDEDOR NUMBER(30);
V_SUELDO_BASE_VENDEDOR NUMBER;
V_ANNIOS_CONTRATADO NUMBER(9);
V_PORC_ANTIGUEDAD NUMBER(3);
V_BONIFICACION_ANTIGUEDAD NUMBER;
V_NUM_CARGAS_FAM NUMBER(3);
V_ASIG_CARGA_FAM NUMBER;
V_ANNIO_PROCESO NUMBER(4);
V_MES_PROCESO NUMBER;
V_MONTO_TOTAL_VENTAS NUMBER;
V_COMISION_VENTAS NUMBER;
V_CATEGORIA_VENDEDOR CHAR(1);
V_PORCENTAJE_CATEGORIA NUMBER(3);
V_BONO_CATEGORIA NUMBER;
V_ID_AFP NUMBER(3);
V_ID_SALUD NUMBER(3);
V_TOTAL_HABERES_FINAL NUMBER;
V_VENTAS_ANUALES NUMBER:= 0;
V_NUEVA_CATEGORIA CHAR(1);
V_MIN NUMBER;
V_MAX NUMBER;
V_OBSERVACION VARCHAR2(30);BEGIN
 EXECUTE IMMEDIATE('TRUNCATE TABLE HABER_MES_VENDEDOR');
 EXECUTE IMMEDIATE('TRUNCATE TABLE DETALLE_MODIF_CATEG_VENDEDOR');
 --MES Y ANNIO PROCESO
 V_ANNIO_PROCESO := SUBSTR(:B_FECHA_PROCESO, -4);
 V_MES_PROCESO := SUBSTR(:B_FECHA_PROCESO, 1, 2);
 
 
 --VALORES PARA BUCLE
 SELECT 
 MIN(ID_VENDEDOR),
 MAX(ID_VENDEDOR)
 INTO
 V_MIN,
 V_MAX
 FROM
 VENDEDOR;
 
 
 WHILE V_MIN <= V_MAX LOOP
 
 
 --OBTENCION DE DATOS BASICOS VENDEDOR
 SELECT
 ID_VENDEDOR,
 RUT_VENDEDOR,
 SUELDO_BASE,
 TRUNC(MONTHS_BETWEEN(SYSDATE,FEC_CONTRATO)/12),
 ID_AFP,
 ID_SALUD
 INTO
 V_ID_VENDEDOR,
 V_RUT_VENDEDOR,
 V_SUELDO_BASE_VENDEDOR,
 V_ANNIOS_CONTRATADO,
 V_ID_AFP,
 V_ID_SALUD
 FROM
 VENDEDOR
 WHERE
 ID_VENDEDOR = V_MIN; --CONTADOR
 
 --PORCENTAJE ASIG ANTIGUEDAD
 SELECT
 NVL(PORC_BONIF, 0)
 INTO
 V_PORC_ANTIGUEDAD
 FROM
 VENDEDOR V
 LEFT JOIN
 BONIFICACION_ANTIG B
 ON
 V_ANNIOS_CONTRATADO
 BETWEEN B.ANNO_TRAMO_INF AND B.ANNO_TRAMO_SUP
 
 WHERE
 ID_VENDEDOR = V_MIN; --CONTADOR
 
 --CALCULO PAGO POR CONCEPTO DE ANTIGUEDAD
 V_BONIFICACION_ANTIGUEDAD:= V_SUELDO_BASE_VENDEDOR * V_PORC_ANTIGUEDAD/100;